""" Organization details to use in the REAL workshop collaborations """

organizations = [
    {
        "name": "Apple Innovations",
        "address1": "123 Apple St",
        "country": "Germany",
        "domain": "appleinnovations.de",
        "zipcode": "10115",
    },
    {
        "name": "Banana Tech Solutions",
        "address1": "456 Banana Ave",
        "country": "France",
        "domain": "bananatech.fr",
        "zipcode": "75001",
    },
    {
        "name": "Cherry Digital",
        "address1": "789 Cherry Blvd",
        "country": "Italy",
        "domain": "cherrydigital.it",
        "zipcode": "00184",
    },
    {
        "name": "Date Palm Technologies",
        "address1": "101 Date Palm Rd",
        "country": "Spain",
        "domain": "datepalmtech.es",
        "zipcode": "28001",
    },
    {
        "name": "Elderberry Enterprises",
        "address1": "202 Elderberry Ln",
        "country": "Netherlands",
        "domain": "elderberryenterprises.nl",
        "zipcode": "1011",
    },
    {
        "name": "Fig Future Tech",
        "address1": "303 Fig St",
        "country": "Belgium",
        "domain": "figfuturetech.be",
        "zipcode": "1000",
    },
    {
        "name": "Grapevine Systems",
        "address1": "404 Grapevine Ave",
        "country": "Sweden",
        "domain": "grapevinesystems.se",
        "zipcode": "111 22",
    },
    {
        "name": "Honeydew Innovations",
        "address1": "505 Honeydew Blvd",
        "country": "Denmark",
        "domain": "honeydewinnovations.dk",
        "zipcode": "1000",
    },
    {
        "name": "Ivy Berry Solutions",
        "address1": "606 Ivy Berry Rd",
        "country": "Norway",
        "domain": "ivyberrysolutions.no",
        "zipcode": "0150",
    },
    {
        "name": "Jackfruit Technologies",
        "address1": "707 Jackfruit Ln",
        "country": "Finland",
        "domain": "jackfruittech.fi",
        "zipcode": "00100",
    },
    {
        "name": "Kiwi Digital",
        "address1": "808 Kiwi St",
        "country": "Switzerland",
        "domain": "kiwidigital.ch",
        "zipcode": "8001",
    },
    {
        "name": "Lemonade Tech",
        "address1": "909 Lemonade Ave",
        "country": "Austria",
        "domain": "lemonadetech.at",
        "zipcode": "1010",
    },
    {
        "name": "Mango Matrix",
        "address1": "1010 Mango Blvd",
        "country": "Portugal",
        "domain": "mangomatrix.pt",
        "zipcode": "1100-001",
    },
    {
        "name": "Nectarine Networks",
        "address1": "1111 Nectarine Rd",
        "country": "Greece",
        "domain": "nectarinenetworks.gr",
        "zipcode": "105 52",
    },
    {
        "name": "Orange Orbit",
        "address1": "1212 Orange Ln",
        "country": "Ireland",
        "domain": "orangeorbit.ie",
        "zipcode": "D01",
    },
    {
        "name": "Papaya Pioneers",
        "address1": "1313 Papaya St",
        "country": "Poland",
        "domain": "papayapioneers.pl",
        "zipcode": "00-001",
    },
    {
        "name": "Quince Quantum",
        "address1": "1414 Quince Ave",
        "country": "Czech Republic",
        "domain": "quincequantum.cz",
        "zipcode": "110 00",
    },
    {
        "name": "Raspberry Revolution",
        "address1": "1515 Raspberry Blvd",
        "country": "Hungary",
        "domain": "raspberryrevolution.hu",
        "zipcode": "1051",
    },
    {
        "name": "Tangerine Tech",
        "address1": "1717 Tangerine Ln",
        "country": "Bulgaria",
        "domain": "tangerinetech.bg",
        "zipcode": "1000",
    },
    {
        "name": "Xigua Xperts",
        "address1": "2121 Xigua Rd",
        "country": "Estonia",
        "domain": "xiguaxperts.ee",
        "zipcode": "10111",
    },
    {
        "name": "Yellow Passionfruit Tech",
        "address1": "2222 Yellow Passionfruit Ln",
        "country": "Latvia",
        "domain": "yellowpassionfruittech.lv",
        "zipcode": "LV-1050",
    },
    {
        "name": "Zucchini Zone",
        "address1": "2323 Zucchini St",
        "country": "Lithuania",
        "domain": "zucchinizone.lt",
        "zipcode": "01100",
    },
    {
        "name": "Blueberry Bytes",
        "address1": "2424 Blueberry Ave",
        "country": "Luxembourg",
        "domain": "blueberrybytes.lu",
        "zipcode": "L-1111",
    },
    {
        "name": "Cantaloupe Cloud",
        "address1": "2525 Cantaloupe Blvd",
        "country": "Malta",
        "domain": "cantaloupecloud.mt",
        "zipcode": "VLT 1111",
    },
    {
        "name": "Dragonfruit Dynamics",
        "address1": "2626 Dragonfruit Rd",
        "country": "Cyprus",
        "domain": "dragonfruitdynamics.cy",
        "zipcode": "1010",
    },
    {
        "name": "Fruit Fusion Tech",
        "address1": "2828 Fruit Fusion St",
        "country": "Liechtenstein",
        "domain": "fruitfusiontech.li",
        "zipcode": "9490",
    },
    {
        "name": "Grapefruit Grid",
        "address1": "2929 Grapefruit Ave",
        "country": "Monaco",
        "domain": "grapefruitgrid.mc",
        "zipcode": "98000",
    },
    {
        "name": "Huckleberry Hub",
        "address1": "3030 Huckleberry Blvd",
        "country": "San Marino",
        "domain": "huckleberryhub.sm",
        "zipcode": "47890",
    },
    {
        "name": "Kiwi Kinetics",
        "address1": "3131 Kiwi Rd",
        "country": "Andorra",
        "domain": "kiwikinetics.ad",
        "zipcode": "AD500",
    },
    {
        "name": "Lime Light Tech",
        "address1": "3232 Lime Ln",
        "country": "Vatican City",
        "domain": "limelighttech.va",
        "zipcode": "00120",
    },
    {
        "name": "Pineapple Paradigm",
        "address1": "3333 Pineapple Blvd",
        "country": "Portugal",
        "domain": "pineappleparadigm.pt",
        "zipcode": "1100-001",
    },
    {
        "name": "Strawberry Systems",
        "address1": "3535 Strawberry Ln",
        "country": "Ireland",
        "domain": "strawberrysystems.ie",
        "zipcode": "D01",
    },
    {
        "name": "Ugli Fruit Innovations",
        "address1": "3737 Ugli Fruit Ave",
        "country": "Czech Republic",
        "domain": "uglifruitinnovations.cz",
        "zipcode": "110 00",
    },
    {
        "name": "Vanilla Ventures",
        "address1": "3838 Vanilla Blvd",
        "country": "Hungary",
        "domain": "vanillaventures.hu",
        "zipcode": "1051",
    },
    {
        "name": "Watermelon Web",
        "address1": "3939 Watermelon Rd",
        "country": "Romania",
        "domain": "watermelonweb.ro",
        "zipcode": "010011",
    },
    {
        "name": "Apricot Analytics",
        "address1": "4040 Apricot St",
        "country": "Switzerland",
        "domain": "apricotanalytics.ch",
        "zipcode": "8001",
    },
    {
        "name": "Cranberry Code",
        "address1": "4242 Cranberry Ln",
        "country": "Finland",
        "domain": "cranberrycode.fi",
        "zipcode": "00100",
    },
    {
        "name": "Grapefruit Group",
        "address1": "4646 Grapefruit Blvd",
        "country": "Luxembourg",
        "domain": "grapefruitgroup.lu",
        "zipcode": "L-1009",
    },
    {
        "name": "Huckleberry Holdings",
        "address1": "4747 Huckleberry Ln",
        "country": "Monaco",
        "domain": "huckleberryholdings.mc",
        "zipcode": "98000",
    },
    {
        "name": "Kumquat Kinetics",
        "address1": "4949 Kumquat Ave",
        "country": "Malta",
        "domain": "kumquatkinetics.mt",
        "zipcode": "VLT 1111",
    },
    {
        "name": "Lychee Labs",
        "address1": "5252 Lychee St",
        "country": "Poland",
        "domain": "lycheelabs.pl",
        "zipcode": "00-001",
    },
    {
        "name": "Mulberry Media",
        "address1": "5353 Mulberry Blvd",
        "country": "Greece",
        "domain": "mulberrymedia.gr",
        "zipcode": "105 58",
    },
]
